# Generated by Django 2.2.2 on 2019-06-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190605_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('000', 'Computer science, information and general works'), ('100', 'Philosophy and psychology'), ('200', 'Religion'), ('300', 'Social Sciences'), ('400', 'Language'), ('500', 'Science'), ('600', 'Technology and applied science'), ('700', 'Arts and recreation'), ('800', 'Literature'), ('900', 'History and geography')], max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=200),
        ),
    ]
