# Generated by Django 2.2.2 on 2019-06-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190605_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AddField(
            model_name='user',
            name='borrow_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrower',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200),
        ),
    ]
