# Generated by Django 2.2.2 on 2019-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190609_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='borrow_amount',
            new_name='current_borrow_amount',
        ),
        migrations.AddField(
            model_name='user',
            name='total_books_borrowed',
            field=models.IntegerField(default=0),
        ),
    ]
