# Generated by Django 2.2.2 on 2019-06-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190612_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_borrow_amount',
        ),
    ]
